language: cpp

sudo: required

git:
  submodules: false

cache:
  ccache: true
  directories:
  - ${HOME}/.ccache

services:
- docker

matrix:
  include:
  - before_install: &before_install
    - sed -i 's;git@github.com:;https://github.com/;' .gitmodules
    - git submodule update --init
    - git submodule foreach --recursive "sed -i 's;git@github.com:;https://github.com/;' .gitmodules; git submodule update --init"
    - docker pull ubuntu:17.10
    - scripts/build_docker_image_build.sh
    env: BUILD_SCRIPT=scripts/build_gcc_debug.sh

  - before_install: *before_install
    env: BUILD_SCRIPT=scripts/build_gcc_rel_with_deb_info.sh

  - before_install: *before_install
    env: BUILD_SCRIPT=scripts/build_clang_debug.sh

  - before_install: *before_install
    env: BUILD_SCRIPT=scripts/build_clang_rel_with_deb_info.sh

  - before_install: *before_install
    env: BUILD_SCRIPT=scripts/build_clang_asan.sh

  - before_install: *before_install
    env: BUILD_SCRIPT=scripts/build_clang_ubsan.sh

script:
- scripts/build_inside_docker_container.sh ${BUILD_SCRIPT}
